dispatcher:
  adapter:
    script:
      - adapter: 1
        adapterClass: something
      - adapter: 2
        adapterClass: similar
  app:
    properties:
      - key: 1
        value: "hello"
      - key: 2
        value: "world"
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=Dispatcher_17_test
    username: sa
    password: Root@1234

server.port: 34355

server.ssl.key-store: keystore.jks
server.ssl.key-store-type: jks
server.ssl.key-store-password: password
#server.ssl.key-password=password
# server.ssl.key-alias=server-service
# server.ssl.client-auth=need

server.ssl.trust-store: truststore.jks
server.ssl.trust-store-password: your_storepass
# ##server.ssl.trust-store-provider= # Provider for the trust store.
server.ssl.trust-store-type: JKS
# logging.level.org.springframework: debug
